"""schema inicial

Revision ID: 93fa24d672da
Revises: 
Create Date: 2026-05-15 16:03:47.097430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fa24d672da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_alocacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=True),
    sa.Column('autonomia_projetada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rodada_alocacao', sa.Integer(), nullable=True),
    sa.Column('tecnologia', sa.String(length=50), nullable=True),
    sa.Column('tensao', sa.Integer(), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ganho', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ganho_por_custo', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('investimento_restante', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indisponibilidade_restante', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_acumulado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ganho_acumulado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ganho_por_milhao_investido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_autonomia_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('tecnologia', sa.String(length=255), nullable=True),
    sa.Column('fabricante', sa.String(length=255), nullable=True),
    sa.Column('tensao', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('capacidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('autonomia_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_autonomia_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_autonomia_inventario_estacao'), ['estacao'], unique=False)

    op.create_table('tb_autonomia_restabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('autonomia_media_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restabelecimento_medio_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_autonomia', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_autonomia_restabelecimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_autonomia_restabelecimento_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_autonomia_restabelecimento_estacao'), ['estacao'], unique=False)

    op.create_table('tb_baterias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnologia', sa.String(length=255), nullable=False),
    sa.Column('fabricante', sa.String(length=255), nullable=False),
    sa.Column('tensao', sa.String(length=255), nullable=True),
    sa.Column('capacidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tecnologia', 'fabricante', 'tensao', 'capacidade', name='uq_baterias_tecnologia_fabricante_tensao_capacidade')
    )
    op.create_table('tb_disponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('disponibilidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disponibilidade_parcial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disponibilidade_energia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('indisponibilidade_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('indisponibilidade_parcial_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('indisponibilidade_energia_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('indisponibilidade_energia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferenca_meta_disponibilidade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferenca_meta_disponibilidade_parcial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferenca_meta_disponibilidade_energia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('incidentes', sa.Integer(), nullable=True),
    sa.Column('incidentes_parcial', sa.Integer(), nullable=True),
    sa.Column('incidentes_energia', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_disponibilidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_disponibilidade_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_disponibilidade_estacao'), ['estacao'], unique=False)

    op.create_table('tb_estacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('ibge', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_estacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_estacoes_cluster'), ['cluster'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_estacoes_estacao'), ['estacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_estacoes_uf'), ['uf'], unique=False)

    op.create_table('tb_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('autonomia_projetada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carga', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pontuacao_hierarquia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_indisponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('submit_date', sa.DateTime(), nullable=False),
    sa.Column('clear_date', sa.DateTime(), nullable=False),
    sa.Column('indisponibilidade_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_indisponibilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_indisponibilidades_estacao'), ['estacao'], unique=False)

    op.create_table('tb_pontuacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=True),
    sa.Column('pontuacao_autonomia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_trafego_dados', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_hierarquia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_tmr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_idade_bateria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_faturamento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao_cliente', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pontuacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_refresh_token_manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('refresh_token_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_trafego_faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacao', sa.String(length=255), nullable=False),
    sa.Column('trafego_dados_ewma', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('faturamento_ewma', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_trafego_faturamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_trafego_faturamento_estacao'), ['estacao'], unique=False)

    op.create_table('tb_user_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users')
    op.drop_table('tb_user_access')
    with op.batch_alter_table('tb_trafego_faturamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_trafego_faturamento_estacao'))

    op.drop_table('tb_trafego_faturamento')
    op.drop_table('tb_refresh_token_manager')
    op.drop_table('tb_pontuacoes')
    with op.batch_alter_table('tb_indisponibilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_indisponibilidades_estacao'))

    op.drop_table('tb_indisponibilidades')
    op.drop_table('tb_features')
    with op.batch_alter_table('tb_estacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_estacoes_uf'))
        batch_op.drop_index(batch_op.f('ix_tb_estacoes_estacao'))
        batch_op.drop_index(batch_op.f('ix_tb_estacoes_cluster'))

    op.drop_table('tb_estacoes')
    with op.batch_alter_table('tb_disponibilidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_disponibilidade_estacao'))
        batch_op.drop_index(batch_op.f('ix_tb_disponibilidade_ano'))

    op.drop_table('tb_disponibilidade')
    op.drop_table('tb_baterias')
    with op.batch_alter_table('tb_autonomia_restabelecimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_autonomia_restabelecimento_estacao'))
        batch_op.drop_index(batch_op.f('ix_tb_autonomia_restabelecimento_ano'))

    op.drop_table('tb_autonomia_restabelecimento')
    with op.batch_alter_table('tb_autonomia_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_autonomia_inventario_estacao'))

    op.drop_table('tb_autonomia_inventario')
    op.drop_table('tb_alocacoes')
    # ### end Alembic commands ###
